language: java
dist: trusty

addons:
  sonarcloud:
    organization: "chiaradia"
    token:
      secure: $SONAR_TOKEN

jdk:
  - oraclejdk8

script:
  - ./mvnw clean install -B
  - ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

cache:
  directories:
    - '$HOME/.sonar/cache'
