server:
  port: 8080

spring:
  profiles:
    include: dev
  application:
    name: stockservice


management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    metrics:
      enabled: false
    prometheus:
      enabled: true
