kind: Service
apiVersion: v1
metadata:
  name: stockservice
  labels:
    app: stockservice
spec:
  selector:
    app: stockservice
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 8080
